version: '3'
services:
  auction:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: "postgres" # use latest official postgres version
    env_file:
      - postgres.env # configure postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  postgres_data: